inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'app/dashboards/*'
    - 'bin/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'config.ru'
    - 'db/schema.rb'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
