version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.0.3-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - ruby/rubocop-check
  rspec:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: trade_test
          MYSQL_USER: user
          MYSQL_PASSWORD: userpass
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Replace capybara.rb
          command: mv ./spec/for_circleci/capybara.rb ./spec/support
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Database setup
          command: |
            bundle exec rails db:migrate
            bundle exec rails db:schema:load --trace
      - ruby/rspec-test

workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - rspec
